// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: services/players_list/players_list.proto

package players_list

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayersListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PlayersListRequest) Reset() {
	*x = PlayersListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_players_list_players_list_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayersListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayersListRequest) ProtoMessage() {}

func (x *PlayersListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_players_list_players_list_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayersListRequest.ProtoReflect.Descriptor instead.
func (*PlayersListRequest) Descriptor() ([]byte, []int) {
	return file_services_players_list_players_list_proto_rawDescGZIP(), []int{0}
}

type PlayersListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Names []string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
}

func (x *PlayersListResponse) Reset() {
	*x = PlayersListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_players_list_players_list_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayersListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayersListResponse) ProtoMessage() {}

func (x *PlayersListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_players_list_players_list_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayersListResponse.ProtoReflect.Descriptor instead.
func (*PlayersListResponse) Descriptor() ([]byte, []int) {
	return file_services_players_list_players_list_proto_rawDescGZIP(), []int{1}
}

func (x *PlayersListResponse) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

var File_services_players_list_players_list_proto protoreflect.FileDescriptor

var file_services_players_list_players_list_proto_rawDesc = []byte{
	0x0a, 0x28, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x73, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x2f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x5f,
	0x6c, 0x69, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x73, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x14, 0x0a, 0x12, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2b,
	0x0a, 0x13, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x32, 0x6b, 0x0a, 0x12, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x55, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x20, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x5f, 0x6c, 0x69,
	0x73, 0x74, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x5f,
	0x6c, 0x69, 0x73, 0x74, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x3e, 0x5a, 0x3c, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x62, 0x68, 0x69, 0x6c, 0x61, 0x73, 0x68, 0x4a,
	0x4e, 0x2f, 0x67, 0x6f, 0x63, 0x73, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x73, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_players_list_players_list_proto_rawDescOnce sync.Once
	file_services_players_list_players_list_proto_rawDescData = file_services_players_list_players_list_proto_rawDesc
)

func file_services_players_list_players_list_proto_rawDescGZIP() []byte {
	file_services_players_list_players_list_proto_rawDescOnce.Do(func() {
		file_services_players_list_players_list_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_players_list_players_list_proto_rawDescData)
	})
	return file_services_players_list_players_list_proto_rawDescData
}

var file_services_players_list_players_list_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_services_players_list_players_list_proto_goTypes = []interface{}{
	(*PlayersListRequest)(nil),  // 0: players_list.PlayersListRequest
	(*PlayersListResponse)(nil), // 1: players_list.PlayersListResponse
}
var file_services_players_list_players_list_proto_depIdxs = []int32{
	0, // 0: players_list.PlayersListService.GetPlayersList:input_type -> players_list.PlayersListRequest
	1, // 1: players_list.PlayersListService.GetPlayersList:output_type -> players_list.PlayersListResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_players_list_players_list_proto_init() }
func file_services_players_list_players_list_proto_init() {
	if File_services_players_list_players_list_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_players_list_players_list_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayersListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_players_list_players_list_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayersListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_players_list_players_list_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_players_list_players_list_proto_goTypes,
		DependencyIndexes: file_services_players_list_players_list_proto_depIdxs,
		MessageInfos:      file_services_players_list_players_list_proto_msgTypes,
	}.Build()
	File_services_players_list_players_list_proto = out.File
	file_services_players_list_players_list_proto_rawDesc = nil
	file_services_players_list_players_list_proto_goTypes = nil
	file_services_players_list_players_list_proto_depIdxs = nil
}
