// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: services/stats_summary/accuracy_summary/accuracy_summary.proto

package accuracy_summary

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccuracySummaryItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Fired         int32  `protobuf:"varint,2,opt,name=fired,proto3" json:"fired,omitempty"`
	Hits          int32  `protobuf:"varint,3,opt,name=hits,proto3" json:"hits,omitempty"`
	HitPercentage string `protobuf:"bytes,4,opt,name=hitPercentage,proto3" json:"hitPercentage,omitempty"`
	Headshots     int32  `protobuf:"varint,5,opt,name=headshots,proto3" json:"headshots,omitempty"`
}

func (x *AccuracySummaryItem) Reset() {
	*x = AccuracySummaryItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_stats_summary_accuracy_summary_accuracy_summary_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccuracySummaryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccuracySummaryItem) ProtoMessage() {}

func (x *AccuracySummaryItem) ProtoReflect() protoreflect.Message {
	mi := &file_services_stats_summary_accuracy_summary_accuracy_summary_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccuracySummaryItem.ProtoReflect.Descriptor instead.
func (*AccuracySummaryItem) Descriptor() ([]byte, []int) {
	return file_services_stats_summary_accuracy_summary_accuracy_summary_proto_rawDescGZIP(), []int{0}
}

func (x *AccuracySummaryItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AccuracySummaryItem) GetFired() int32 {
	if x != nil {
		return x.Fired
	}
	return 0
}

func (x *AccuracySummaryItem) GetHits() int32 {
	if x != nil {
		return x.Hits
	}
	return 0
}

func (x *AccuracySummaryItem) GetHitPercentage() string {
	if x != nil {
		return x.HitPercentage
	}
	return ""
}

func (x *AccuracySummaryItem) GetHeadshots() int32 {
	if x != nil {
		return x.Headshots
	}
	return 0
}

type AccuracySummary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Category string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Items    []*AccuracySummaryItem `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *AccuracySummary) Reset() {
	*x = AccuracySummary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_stats_summary_accuracy_summary_accuracy_summary_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccuracySummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccuracySummary) ProtoMessage() {}

func (x *AccuracySummary) ProtoReflect() protoreflect.Message {
	mi := &file_services_stats_summary_accuracy_summary_accuracy_summary_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccuracySummary.ProtoReflect.Descriptor instead.
func (*AccuracySummary) Descriptor() ([]byte, []int) {
	return file_services_stats_summary_accuracy_summary_accuracy_summary_proto_rawDescGZIP(), []int{1}
}

func (x *AccuracySummary) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *AccuracySummary) GetItems() []*AccuracySummaryItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type AllAccuracySummaries struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*AccuracySummary `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *AllAccuracySummaries) Reset() {
	*x = AllAccuracySummaries{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_stats_summary_accuracy_summary_accuracy_summary_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllAccuracySummaries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllAccuracySummaries) ProtoMessage() {}

func (x *AllAccuracySummaries) ProtoReflect() protoreflect.Message {
	mi := &file_services_stats_summary_accuracy_summary_accuracy_summary_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllAccuracySummaries.ProtoReflect.Descriptor instead.
func (*AllAccuracySummaries) Descriptor() ([]byte, []int) {
	return file_services_stats_summary_accuracy_summary_accuracy_summary_proto_rawDescGZIP(), []int{2}
}

func (x *AllAccuracySummaries) GetData() []*AccuracySummary {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_services_stats_summary_accuracy_summary_accuracy_summary_proto protoreflect.FileDescriptor

var file_services_stats_summary_accuracy_summary_accuracy_summary_proto_rawDesc = []byte{
	0x0a, 0x3e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x73,
	0x5f, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x2f, 0x61, 0x63, 0x63, 0x75, 0x72, 0x61, 0x63,
	0x79, 0x5f, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x2f, 0x61, 0x63, 0x63, 0x75, 0x72, 0x61,
	0x63, 0x79, 0x5f, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x10, 0x61, 0x63, 0x63, 0x75, 0x72, 0x61, 0x63, 0x79, 0x5f, 0x73, 0x75, 0x6d, 0x6d, 0x61,
	0x72, 0x79, 0x22, 0x97, 0x01, 0x0a, 0x13, 0x41, 0x63, 0x63, 0x75, 0x72, 0x61, 0x63, 0x79, 0x53,
	0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x66, 0x69, 0x72, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x66,
	0x69, 0x72, 0x65, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x69, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x68, 0x69, 0x74, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x68, 0x69, 0x74, 0x50,
	0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x68, 0x69, 0x74, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x68, 0x65, 0x61, 0x64, 0x73, 0x68, 0x6f, 0x74, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x68, 0x65, 0x61, 0x64, 0x73, 0x68, 0x6f, 0x74, 0x73, 0x22, 0x6a, 0x0a, 0x0f,
	0x41, 0x63, 0x63, 0x75, 0x72, 0x61, 0x63, 0x79, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12,
	0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x3b, 0x0a, 0x05, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x61, 0x63, 0x63,
	0x75, 0x72, 0x61, 0x63, 0x79, 0x5f, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x2e, 0x41, 0x63,
	0x63, 0x75, 0x72, 0x61, 0x63, 0x79, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x4d, 0x0a, 0x14, 0x41, 0x6c, 0x6c, 0x41,
	0x63, 0x63, 0x75, 0x72, 0x61, 0x63, 0x79, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x69, 0x65, 0x73,
	0x12, 0x35, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21,
	0x2e, 0x61, 0x63, 0x63, 0x75, 0x72, 0x61, 0x63, 0x79, 0x5f, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72,
	0x79, 0x2e, 0x41, 0x63, 0x63, 0x75, 0x72, 0x61, 0x63, 0x79, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72,
	0x79, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x50, 0x5a, 0x4e, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x62, 0x68, 0x69, 0x6c, 0x61, 0x73, 0x68, 0x4a, 0x4e,
	0x2f, 0x67, 0x6f, 0x63, 0x73, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x73,
	0x5f, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x2f, 0x61, 0x63, 0x63, 0x75, 0x72, 0x61, 0x63,
	0x79, 0x5f, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_services_stats_summary_accuracy_summary_accuracy_summary_proto_rawDescOnce sync.Once
	file_services_stats_summary_accuracy_summary_accuracy_summary_proto_rawDescData = file_services_stats_summary_accuracy_summary_accuracy_summary_proto_rawDesc
)

func file_services_stats_summary_accuracy_summary_accuracy_summary_proto_rawDescGZIP() []byte {
	file_services_stats_summary_accuracy_summary_accuracy_summary_proto_rawDescOnce.Do(func() {
		file_services_stats_summary_accuracy_summary_accuracy_summary_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_stats_summary_accuracy_summary_accuracy_summary_proto_rawDescData)
	})
	return file_services_stats_summary_accuracy_summary_accuracy_summary_proto_rawDescData
}

var file_services_stats_summary_accuracy_summary_accuracy_summary_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_services_stats_summary_accuracy_summary_accuracy_summary_proto_goTypes = []interface{}{
	(*AccuracySummaryItem)(nil),  // 0: accuracy_summary.AccuracySummaryItem
	(*AccuracySummary)(nil),      // 1: accuracy_summary.AccuracySummary
	(*AllAccuracySummaries)(nil), // 2: accuracy_summary.AllAccuracySummaries
}
var file_services_stats_summary_accuracy_summary_accuracy_summary_proto_depIdxs = []int32{
	0, // 0: accuracy_summary.AccuracySummary.items:type_name -> accuracy_summary.AccuracySummaryItem
	1, // 1: accuracy_summary.AllAccuracySummaries.data:type_name -> accuracy_summary.AccuracySummary
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_services_stats_summary_accuracy_summary_accuracy_summary_proto_init() }
func file_services_stats_summary_accuracy_summary_accuracy_summary_proto_init() {
	if File_services_stats_summary_accuracy_summary_accuracy_summary_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_stats_summary_accuracy_summary_accuracy_summary_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccuracySummaryItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_stats_summary_accuracy_summary_accuracy_summary_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccuracySummary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_stats_summary_accuracy_summary_accuracy_summary_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllAccuracySummaries); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_stats_summary_accuracy_summary_accuracy_summary_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_services_stats_summary_accuracy_summary_accuracy_summary_proto_goTypes,
		DependencyIndexes: file_services_stats_summary_accuracy_summary_accuracy_summary_proto_depIdxs,
		MessageInfos:      file_services_stats_summary_accuracy_summary_accuracy_summary_proto_msgTypes,
	}.Build()
	File_services_stats_summary_accuracy_summary_accuracy_summary_proto = out.File
	file_services_stats_summary_accuracy_summary_accuracy_summary_proto_rawDesc = nil
	file_services_stats_summary_accuracy_summary_accuracy_summary_proto_goTypes = nil
	file_services_stats_summary_accuracy_summary_accuracy_summary_proto_depIdxs = nil
}
