// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: services/heatmap/heatmap.proto

package heatmap

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeatmapRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player string `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
}

func (x *HeatmapRequest) Reset() {
	*x = HeatmapRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_heatmap_heatmap_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeatmapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeatmapRequest) ProtoMessage() {}

func (x *HeatmapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_heatmap_heatmap_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeatmapRequest.ProtoReflect.Descriptor instead.
func (*HeatmapRequest) Descriptor() ([]byte, []int) {
	return file_services_heatmap_heatmap_proto_rawDescGZIP(), []int{0}
}

func (x *HeatmapRequest) GetPlayer() string {
	if x != nil {
		return x.Player
	}
	return ""
}

type HeatmapPoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float64 `protobuf:"fixed64,1,opt,name=X,proto3" json:"X,omitempty"`
	Y float64 `protobuf:"fixed64,2,opt,name=Y,proto3" json:"Y,omitempty"`
}

func (x *HeatmapPoint) Reset() {
	*x = HeatmapPoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_heatmap_heatmap_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeatmapPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeatmapPoint) ProtoMessage() {}

func (x *HeatmapPoint) ProtoReflect() protoreflect.Message {
	mi := &file_services_heatmap_heatmap_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeatmapPoint.ProtoReflect.Descriptor instead.
func (*HeatmapPoint) Descriptor() ([]byte, []int) {
	return file_services_heatmap_heatmap_proto_rawDescGZIP(), []int{1}
}

func (x *HeatmapPoint) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *HeatmapPoint) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type HeatmapResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kill      []*HeatmapPoint `protobuf:"bytes,1,rep,name=kill,proto3" json:"kill,omitempty"`
	Death     []*HeatmapPoint `protobuf:"bytes,2,rep,name=death,proto3" json:"death,omitempty"`
	BombPlant []*HeatmapPoint `protobuf:"bytes,3,rep,name=bomb_plant,json=bombPlant,proto3" json:"bomb_plant,omitempty"`
}

func (x *HeatmapResponse) Reset() {
	*x = HeatmapResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_heatmap_heatmap_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeatmapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeatmapResponse) ProtoMessage() {}

func (x *HeatmapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_heatmap_heatmap_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeatmapResponse.ProtoReflect.Descriptor instead.
func (*HeatmapResponse) Descriptor() ([]byte, []int) {
	return file_services_heatmap_heatmap_proto_rawDescGZIP(), []int{2}
}

func (x *HeatmapResponse) GetKill() []*HeatmapPoint {
	if x != nil {
		return x.Kill
	}
	return nil
}

func (x *HeatmapResponse) GetDeath() []*HeatmapPoint {
	if x != nil {
		return x.Death
	}
	return nil
}

func (x *HeatmapResponse) GetBombPlant() []*HeatmapPoint {
	if x != nil {
		return x.BombPlant
	}
	return nil
}

var File_services_heatmap_heatmap_proto protoreflect.FileDescriptor

var file_services_heatmap_heatmap_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x68, 0x65, 0x61, 0x74, 0x6d,
	0x61, 0x70, 0x2f, 0x68, 0x65, 0x61, 0x74, 0x6d, 0x61, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x07, 0x68, 0x65, 0x61, 0x74, 0x6d, 0x61, 0x70, 0x22, 0x28, 0x0a, 0x0e, 0x48, 0x65, 0x61,
	0x74, 0x6d, 0x61, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x22, 0x2a, 0x0a, 0x0c, 0x48, 0x65, 0x61, 0x74, 0x6d, 0x61, 0x70, 0x50, 0x6f,
	0x69, 0x6e, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x58, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01,
	0x58, 0x12, 0x0c, 0x0a, 0x01, 0x59, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x59, 0x22,
	0x9f, 0x01, 0x0a, 0x0f, 0x48, 0x65, 0x61, 0x74, 0x6d, 0x61, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x04, 0x6b, 0x69, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x68, 0x65, 0x61, 0x74, 0x6d, 0x61, 0x70, 0x2e, 0x48, 0x65, 0x61, 0x74,
	0x6d, 0x61, 0x70, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x04, 0x6b, 0x69, 0x6c, 0x6c, 0x12, 0x2b,
	0x0a, 0x05, 0x64, 0x65, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x68, 0x65, 0x61, 0x74, 0x6d, 0x61, 0x70, 0x2e, 0x48, 0x65, 0x61, 0x74, 0x6d, 0x61, 0x70, 0x50,
	0x6f, 0x69, 0x6e, 0x74, 0x52, 0x05, 0x64, 0x65, 0x61, 0x74, 0x68, 0x12, 0x34, 0x0a, 0x0a, 0x62,
	0x6f, 0x6d, 0x62, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x68, 0x65, 0x61, 0x74, 0x6d, 0x61, 0x70, 0x2e, 0x48, 0x65, 0x61, 0x74, 0x6d, 0x61,
	0x70, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x09, 0x62, 0x6f, 0x6d, 0x62, 0x50, 0x6c, 0x61, 0x6e,
	0x74, 0x32, 0x5a, 0x0a, 0x0e, 0x48, 0x65, 0x61, 0x74, 0x6d, 0x61, 0x70, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x48, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x48, 0x65, 0x61, 0x74, 0x6d, 0x61,
	0x70, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x17, 0x2e, 0x68, 0x65, 0x61,
	0x74, 0x6d, 0x61, 0x70, 0x2e, 0x48, 0x65, 0x61, 0x74, 0x6d, 0x61, 0x70, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x68, 0x65, 0x61, 0x74, 0x6d, 0x61, 0x70, 0x2e, 0x48, 0x65,
	0x61, 0x74, 0x6d, 0x61, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x39, 0x5a,
	0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x62, 0x68, 0x69,
	0x6c, 0x61, 0x73, 0x68, 0x4a, 0x4e, 0x2f, 0x67, 0x6f, 0x63, 0x73, 0x2d, 0x67, 0x72, 0x70, 0x63,
	0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x2f, 0x68, 0x65, 0x61, 0x74, 0x6d, 0x61, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_heatmap_heatmap_proto_rawDescOnce sync.Once
	file_services_heatmap_heatmap_proto_rawDescData = file_services_heatmap_heatmap_proto_rawDesc
)

func file_services_heatmap_heatmap_proto_rawDescGZIP() []byte {
	file_services_heatmap_heatmap_proto_rawDescOnce.Do(func() {
		file_services_heatmap_heatmap_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_heatmap_heatmap_proto_rawDescData)
	})
	return file_services_heatmap_heatmap_proto_rawDescData
}

var file_services_heatmap_heatmap_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_services_heatmap_heatmap_proto_goTypes = []interface{}{
	(*HeatmapRequest)(nil),  // 0: heatmap.HeatmapRequest
	(*HeatmapPoint)(nil),    // 1: heatmap.HeatmapPoint
	(*HeatmapResponse)(nil), // 2: heatmap.HeatmapResponse
}
var file_services_heatmap_heatmap_proto_depIdxs = []int32{
	1, // 0: heatmap.HeatmapResponse.kill:type_name -> heatmap.HeatmapPoint
	1, // 1: heatmap.HeatmapResponse.death:type_name -> heatmap.HeatmapPoint
	1, // 2: heatmap.HeatmapResponse.bomb_plant:type_name -> heatmap.HeatmapPoint
	0, // 3: heatmap.HeatmapService.GetHeatmapPositions:input_type -> heatmap.HeatmapRequest
	2, // 4: heatmap.HeatmapService.GetHeatmapPositions:output_type -> heatmap.HeatmapResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_services_heatmap_heatmap_proto_init() }
func file_services_heatmap_heatmap_proto_init() {
	if File_services_heatmap_heatmap_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_heatmap_heatmap_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeatmapRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_heatmap_heatmap_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeatmapPoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_heatmap_heatmap_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeatmapResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_heatmap_heatmap_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_heatmap_heatmap_proto_goTypes,
		DependencyIndexes: file_services_heatmap_heatmap_proto_depIdxs,
		MessageInfos:      file_services_heatmap_heatmap_proto_msgTypes,
	}.Build()
	File_services_heatmap_heatmap_proto = out.File
	file_services_heatmap_heatmap_proto_rawDesc = nil
	file_services_heatmap_heatmap_proto_goTypes = nil
	file_services_heatmap_heatmap_proto_depIdxs = nil
}
